# Generated by Django 4.2.3 on 2023-08-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacherextraform'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextraform',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
