# Generated by Django 4.2.3 on 2023-08-22 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0004_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='roll_no',
            new_name='present_choices',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present_status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='roll',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
