# Generated by Django 4.2.3 on 2023-08-23 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_attendance_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('posted_by', models.CharField(default='school', max_length=20, null=True)),
                ('posted_on', models.DateField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
            ],
        ),
    ]
