# Generated by Django 4.2.3 on 2023-08-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.CharField(max_length=30),
        ),
    ]
